export default {
    'rects': [
        {
            'width': 200,
            'height': 150,
            'top': 10,
            'left': 10,
            'draggable': true,
            'resizable': true,
            'minw': 10,
            'minh': 10,
            'axis': 'both',
            'parentLim': true,
            'snapToGrid': false,
            'aspectRatio': false,
            'zIndex': 1,
            'color': '#EF9A9A',
            'active': false
        },
        {
            'width': 200,
            'height': 150,
            'top': 10,
            'left': 220,
            'draggable': true,
            'resizable': true,
            'minw': 10,
            'minh': 10,
            'axis': 'both',
            'parentLim': true,
            'snapToGrid': false,
            'aspectRatio': false,
            'zIndex': 1,
            'color': '#E6C27A',
            'active': false,
        },
        {
            'width': 200,
            'height': 150,
            'top': 170,
            'left': 10,
            'draggable': true,
            'resizable': true,
            'minw': 10,
            'minh': 10,
            'axis': 'both',
            'parentLim': true,
            'snapToGrid': false,
            'aspectRatio': false,
            'zIndex': 2,
            'color': '#AED581',
            'active': false,
            'stickStyle': 'none',
            'stickHoverStyle': 'none'
        },
        {
            'width': 200,
            'height': 150,
            'top': 170,
            'left': 220,
            'draggable': true,
            'resizable': true,
            'minw': 200,
            'minh': 50,
            'maxw': 400,
            'maxh': 400,
            'stickSize': 20,
            'axis': 'both',
            'parentLim': true,
            'snapToGrid': false,
            'aspectRatio': false,
            'zIndex': 3,
            'color': '#81D4FA',
            'active': true,
            'stickStyle': 'none',
            'stickHoverStyle': 'box-shadow',
            'zoomTransition': 'all 0.3s ease-out',
        },
        // {
        //     'width': 330,
        //     'height': 1114,
        //     'top': 90,
        //     'left': 660,
        //     'draggable': false,
        //     'minw': 330,
        //     'maxw': 760,
        //     'zIndex': 1000,
        //     'color': '#81D4FA',
        //     'active': true,
        //     'sticks': ['ml'],
        //     'stickStyle': 'none',
        //     'stickHoverStyle': 'none'
        // }
    ]
};
